---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "manager.name" . }}-user-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
    {{- if .Values.secretLabels }}
    {{- toYaml .Values.secretLabels | nindent 4}}
    {{- end }}
  {{- if .Values.secretAnnotations }}
  annotations: {{- toYaml .Values.secretAnnotations | nindent 4}}
  {{- end }}
type: Opaque
stringData:
  {{- range .Values.users }}
  {{ .username | quote }}: {{ .password | quote }}
  {{- end }}
